apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
        - name: invoice-app
          image: gurureddy097/invoice-processing-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
